customhost = "employee.ci5tomydw36w.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployee"
customregion = "ap-south-1"
